### PR TITLE
Update logger_main.py

### PR DESCRIPTION
**Pull request by nixilus**
localtime

### CODE REVIEW

**Comment by guolivar** [comment]
Thanks for the contributions!
I'll merge the pull but I'll change a couple of things after that
1.- "localtime". This may seem as a personal preference but the target for this logger is to generate data for NIWA (www.niwa.co.nz) databases and because of the "daylight saving" issue we need to maintain our data streams on UTC and convert to local time _if required_. So, I'll add a flag on the settings file so that the user can choose between localtime and UTC
2.- Output file name. I require that the file names still comply with the "8.3" format so that they are compatible with some very old internal systems at NIWA. That may change in the future so I'll add another flag to the settings file so the user can choose the format of the output filename (compressed: YYYYMMDD.tsv or extended:YYY-MM-DD.tsv)

**Comment by nixilus** [comment]
NIWA - cool organization.
"localtime", "tsv" and other - it's personal preference, I have a "pet project" to read data from CO2-metr(AZ7722).
Next, I'm add data parsing(import re) and writing to the database(mongoldb or sqlite)
I think that data parsing is so personal, but writing to the database I send too

**Comment by guolivar** [comment]
You're right that it is very dependent on the specific project but it makes sense to give the user a choice.
This logger is meant to be simple, that's why I didn't implement a db connection as I have in other logger (have a look at the CPC3775 logger https://github.com/guolivar/cpc3775_logger ).
If you think that your modifications are useful, send them up!

That CO2 meter seems interesting, we've used mostly Q-Trak from TSI.

**Comment by nixilus** [comment]
Yes CPC3775 logger is interesting, thx. I want to use raspberry pi, postgreSQL is overkill for this task, but not a problem remake it.
I want to use part of your code under the MIT license, if you do not mind

**Pull request merged**
